### ISSUE TITLE
TTS sem áudio

### ISSUE THREAD

**Issue by Teuuz1994** [totalvoice/totalvoice-node#10]
estava utilizando a API normalmente, mas de repente a API parou de funcionar, faz ligações sem áudio algum o tempo todo, estou respeitando a quantidade de caracteres que suporta mas mesmo assim o problema persiste.

abaixo deixarei um exemplo de código da forma que estou implementado e o log:

**código:**

```
const totalVoice = require('totalvoice-node');
const client = new totalVoice('my token');   // no código o token é adicionado corretamente.
const opcoes = { velocidade: 2, tipo_voz: 'br-Vitoria' }

function voice() {
    

    client.tts.enviar('my number', 'Caro Matheus o totalvoice funcionou.', opcoes)
    .then(result => {
        console.log(result);
    }).catch(err => {
        console.log(err);
    })

};

voice();
```

**log do console:**

```
{
  status: 200,
  sucesso: true,
  motivo: 0,
  mensagem: 'tts criado com sucesso',
  dados: { id: 76395301 }
}
```

**Comment by dilowagner** [comment]
Fala @Teuuz1994 blz?

Cara, me parece que ouve alguma instabilidade momentanea na plataforma... ate porque o seu TTS foi criado com sucesso, nao parece ser problema da lib aqui...

Mas o problema ainda esta acontecendo? Se sim, sugiro entrar em contato com o nosso suporte pelo Chat ou pelo e-mail suporte@zenvia.com.

Valeu, abraco!

**Comment by Teuuz1994** [comment]
Obrigado @dilowagner !
o problema ainda continua persistindo, as ligações são feitas com sucesso, porém, sem áudio, vou entrar em contato com o suporte técnico valeu pela dica. 👍
