### ISSUE TITLE
interceptor.js - TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by acaciomartins** [totalvoice/totalvoice-node#12]
Criei uma function no Firebase para envio de SMS e ocorre o erro abaixo quando realizo testes:

```
TypeError: Cannot read property 'data' of undefined
    at defaultReject (/srv/node_modules/totalvoice-node/lib/interceptor.js:9:30)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

O teste quando realizado localmente pelo "firebase emulators:start" não apresenta problemas.

Há alguma configuração adicional para Firebase Functions?

**Comment by dilowagner** [comment]
Ola @acaciomartins 
Sinceramente, desconheco o Firebase... 
Mas pelo que parece eh algo relacionado ao axios. Vc consegue confirmar se ele esta carregando todas as dependencias corretamente na node_modules? Qual versao do NodeJS esta utilizando?

**Comment by acaciomartins** [comment]
Não consegui ver o node_modules no Firebase, estou tentando localizar.

O interessante é que pelo emulators do Firebase Cli funciona, não sei se nesse caso ele roda com as dependências locais.

Testei com Node 8 e 10.

**Comment by acaciomartins** [comment]
Funcionou, analisei o log e foi só ativar minha conta de faturamento do Google.

**Comment by dilowagner** [comment]
hum, deu certo entao?
Interessante saber disso...

**Comment by acaciomartins** [comment]
> hum, deu certo entao?
> Interessante saber disso...

Sim, funcionou perfeitamente.

O problema era justamente minha conta do Google não estar ativa para cobranças.

Obrigado pela ajuda, pois vou fazer um tutorial de como criar Firebase Functions enviado SMS pelo Totalvoice para meu canal!

**Comment by dilowagner** [comment]
Show man...
Valeu e abraço!
