### ISSUE TITLE
[Dúvida] Suporte ao React Native

### ISSUE THREAD

**Issue by imdanielpiva** [totalvoice/totalvoice-node#9]
Olá, pessoal, pelo que investiguei na lib não vi nenhuma dependência que dependa exclusivamente no Node.js, como fs, path etc. Encontrei apenas o Axios e chamadas HTTP/HTTPS, o que não seria um impedimento, mas ainda sim gostaria de perguntar se haveria alguma restrição em usar a biblioteca totalinvoice-node fora do contexto do Node.js.

**Comment by andrewronscki** [comment]
Boa tarte, Daniel Piva, não existe restrição. É possível utilizar a api  sem problemas. 

Para exemplificar criei um app utilizando React Native  + Expo, link do repositório é https://github.com/andrewronscki/utilizando-api-totalvoice-react-native. 

Vale lembrar que é sempre bom ter um Backend  para as UI's, para evitar brechas de segurança, como por exemplo, vazamento de dados sensíveis. 

Um exemplo de dado que não é legal estar na UI neste caso é o Access-Token que se outras pessoas tiverem acesso poderão utilizar a api da Totalvoice com seus créditos.
